# Generated by Django 4.1.5 on 2023-01-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=45)),
                ('production_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('registration_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=9)),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='carrental.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='carrental.customer')),
            ],
        ),
    ]
