# Generated by Django 4.1.2 on 2022-10-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=45)),
                ('production_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('registration_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.rental')),
            ],
        ),
    ]
