# Generated by Django 4.1.2 on 2022-11-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_accident_delete_accidents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='asd', max_length=45),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(default='23', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='asd', max_length=45),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='11-111', max_length=6),
        ),
        migrations.AlterField(
            model_name='accident',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='car_rental.rental'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='type',
            field=models.CharField(choices=[('C', 'Car collision'), ('B', 'Car breakdown'), ('O', 'Other accident')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='car_rental.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='car_rental.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rental.car'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rental.customer'),
        ),
    ]
