# Generated by Django 4.1.2 on 2022-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_rename_name_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='customer',
            name='house_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
